In [1]:
import numpy as np 
from pathlib import Path
from src.data_io.raw_mt import read_pytweezers

file_path = Path(
    "/Volumes/data.yoda.vu.nl/research-beta-pa-dulin-lab/Luca_ops_RfaH_TXonly/20241120_TEC0701_OF_7pN_r5000/TXofp7_r5000/traces.npy"
)
read_pytweezers(file_path)



(array([[[   51.64146423,   220.04013062,  3614.90898132],
         [   41.95842743,   195.2381134 ,  3611.69471741],
         [   79.16240692,   206.2210083 ,  3611.63101196],
         ...,
         [  715.56587219,   545.87249756,  3942.10739136],
         [  719.23789978,   521.39434814,  3940.18783569],
         [  717.09060669,   545.00694275,  3947.66120911]],
 
        [[  -12.56046295,   132.58285522,  3617.04444885],
         [   -8.32824707,   111.08322144,  3606.26564026],
         [  -10.31532288,   118.52264404,  3612.86659241],
         ...,
         [  805.44548035,   480.31387329,  3773.98376465],
         [  816.61605835,   479.13627625,  3776.34010315],
         [  824.55101013,   495.9980011 ,  3783.17871094]],
 
        [[  158.73889923,    85.74295044,  3624.67727661],
         [  144.67983246,   102.10399628,  3623.54125977],
         [  150.6280899 ,    93.78356934,  3622.95036316],
         ...,
         [-1179.52041626,   877.90908813,  -823.75621796],
        

In [2]:
axis_scale

array([120., 120.,  50.])

In [4]:
axis_scale


array([120., 120.,  50.])

In [24]:
names = ('x', 'y','z')

x1 = np.array([1.0]* 100)
y1 = np.array([1.0] * 100)
z1 = np.array([1.0] * 100)

x2 = np.array([2.0] * 200)
y2 = np.array([2.0] * 200)
z2 = np.array([2.0] * 200)
values = [('x1', 'y1', 'z1'), ('x2','y2','z2')]
values_dict = {name: array for name, array in zip(names, zip(*values)  )}
array_dict = {name: np.array(array, dtype=object) for name, array in values_dict.items()}
print(list(zip(*values)))

print(values_dict)
print(array_dict)

[('x1', 'x2'), ('y1', 'y2'), ('z1', 'z2')]
{'x': ('x1', 'x2'), 'y': ('y1', 'y2'), 'z': ('z1', 'z2')}
{'x': array(['x1', 'x2'], dtype=object), 'y': array(['y1', 'y2'], dtype=object), 'z': array(['z1', 'z2'], dtype=object)}
